### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by matthewgardner** [Scrin/RuuviCollector#20]
How are you running locally to test it? (mac or pc?) 
Googling/searching around Bluez isnt supported on Mac or PC - have you stored locally some streamed data that your replay, via a test class back into the main class?

Trying to work out how you built this project :)

**Comment by Scrin** [comment]
When I'm doing development on one of my Linux machines, I use hcitool and hcidump directly as it's by default. When I happen to do development on my Windows machine, I have initially enabled [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on the machine, generated a SSH key and added that key to other Linux machines (and raspberry pi's). This should probably work with some command-line windows ssh client too, but I use WSL for other reasons too so it was the easiest choice.

Then finally I have this in my collector config:

```command.dump=bash -c "ssh user@192.168.1.xxx hcidump --raw"```

which effectively runs hcidump over ssh from another Linux computer/rpi through WSL. Before this I used to have a text file containing a dump gathered from another machine and then as the dump command I just read the file (`command.dump=cmd /c "type hcidump.txt"`), but it became a bit cumbersome as it all pops all the data instantly and it's the same data over and over again.

I have also put an empty `command.scan=` to disable the scan command, and instead run `hcitool lescan --duplicates --passive` manually on the device where hcidump actually runs on, as this allows me to simulate situations where there's a pause in the data flow by stopping the hcitool command and starting it again, although it could be done over ssh the same way as the dump.

I don't have any macs, but the same hcidump-over-ssh trick should work equally fine on macs

**Comment by matthewgardner** [comment]
Awesome - thanks :)
