### ISSUE TITLE
Feature: HttpDBConnection

### ISSUE THREAD

**Issue by Scrin** [Scrin/RuuviCollector#24]
A HttpDBConnection that will do a HTTP POST to a configurable http/https url, with the measurement data encoded as a JSON object with the field names as described in https://github.com/Scrin/RuuviCollector/blob/master/MEASUREMENTS.md

**Comment by matthewgardner** [comment]
Would it not also include the mac &/or name of the device?

I'll see if I can get something working for something like Azure Time Series Insights. Then we can look to make something more generic perhaps :)

**Comment by Scrin** [comment]
yes, mac, and name if it exists

**Comment by matthewgardner** [comment]
Do you see the Ruuvi only hitting one implementation of DBConnection? Or do you see it hitting multiple? 🤔 For example - local and remote data stores?

**Comment by Scrin** [comment]
Multiple, though until the "multiple inputs and multiple outputs" feature I'm working on is done, this will be limited to at most one InfluxDBConnection and one HttpDBConnection at once.

Leaving the configurable url for influx empty (localhost by default) should disable the InfluxDBConnection, and leaving the url for this http endpoint empty (empty by default) should disable the HttpDBConnection.

**Comment by matthewgardner** [comment]
The "multiple inputs and multiple outputs" feature- is there an issue for this? (or something off books :) )

**Comment by Scrin** [comment]
There is now, https://github.com/Scrin/RuuviCollector/issues/34

**Comment by Scrin** [comment]
https://github.com/Scrin/RuuviCollector/issues/34#issuecomment-645587126
