### ISSUE TITLE
Feature: filter.mode=named

### ISSUE THREAD

**Issue by Scrin** [Scrin/RuuviCollector#26]
Currently there 3 different filter modes configurable:
```
# none      = Allows any source to be stored (default)
# blacklist = Allows all sources EXCEPT those listed
# whitelist = Allows ONLY sources that are listed
```
and a 4th mode should be added called `named` which will operate like the whitelist, but only allow tags (macs) that have an associated name in `ruuvi-names.properties`.

It should ignore the `filter.macs` configuration property (like `none` does), and it should throw an IllegalStateException if no names are defined when using this filter mode, just like the `whitelist` does now when using it and no macs are defined.

**Comment by matthewgardner** [comment]
I can do this next :)

**Comment by Scrin** [comment]
go ahead 👍
