### ISSUE TITLE
Feature: Multiple-input-multiple-output

### ISSUE THREAD

**Issue by Scrin** [Scrin/RuuviCollector#34]
- Support for multiple simultaneous input sources of the same type
- Support for multiple simultaneous outputs of the same type
- Redesign some of the config format to support configuring things like this

**Comment by matthewgardner** [comment]
I'm working on a few additional features/outcomes that would benefit from this feature :)
For example
- subscriber - temp gets to a given temp - call a url 
- publisher - power usage on a smart switch (tho this might not be a natural fit to this project) 🤔

**Comment by Scrin** [comment]
Things have changed and I'm actually working on another project which would support this kind of behavior and thus I'm going to implement this kind of feature there, and leave RuuviCollector as a "standalone RuuviTag-to-InfluxDB solution".
