### ISSUE TITLE
All files should use LF line-endings

### ISSUE THREAD

**Issue by nikobockerman** [Scrin/RuuviCollector#35]
Hi,

currently the files in this repository have a mixture of LF and CRLF line-endings. Should all the files have LF line-endings?
Based on the last comment to this pull request [PR 10 comment](https://github.com/Scrin/RuuviCollector/pull/10#discussion_r247308211) it seems that the desire would be to have only LF line-endings.

There are many instructions about how to convert repository to only have LF line-endings:
- [https://help.github.com/en/articles/dealing-with-line-endings](https://help.github.com/en/articles/dealing-with-line-endings)
Contains good documentation but not so good commands to perform the conversion
- [https://stackoverflow.com/a/15646791](https://stackoverflow.com/a/15646791)
Shows working commands for many different git client versions

The simplest way to achieve this is to add .gitattributes file and then running "git add --renormalize ." to convert all files accordingly.

**Comment by Scrin** [comment]
You are correct; the desire is to have LF line endings only. I've been postponing this "normalization" with the idea that I'll be doing it as I release the "1.0.0" version soon after https://github.com/Scrin/RuuviCollector/issues/34 (and possibly https://github.com/Scrin/RuuviCollector/issues/22 ) is implemented, as it will have other "significant and breaking changes" too, and I think it's better to "break things" once than each case separately
