### ISSUE TITLE
Feature request/idea: Offset values to collected measurements

### ISSUE THREAD

**Issue by Boulder08** [Scrin/RuuviCollector#43]
As the Ruuvi tags have some differences in the measured values, it would be good to be able to use some offset values to the data that is stored in the database. For example, when checking for the air pressure difference between tags outdoors and indoors, using normalized values is quite essential.

**Comment by ojousima** [comment]
Personally I've set the offset while displaying the data, for example in Grafana with math-functions. 

Offsets are also somewhat problematic, as they tend to drift over time. Here's an example of 2 tags which were normalized to show same value indoors and one was moved outdoors.
![image](https://user-images.githubusercontent.com/2360368/70596944-bec5f700-1bef-11ea-904e-0367d7a31fdb.png)

As you can see the pressure offset drifts eventually over the course of few days and this drift is larger than the difference in my home ventilation switching between power levels.
