### ISSUE TITLE
raw packet storing

### ISSUE THREAD

**Issue by DG12** [Scrin/RuuviCollector#45]
I wonder if you would consider creating an option for ruuviCollector (or a totally independent application)
which very simply inserts any messages with the manufacturer ID of 0x0499 (or a list of configurable ID) into an influxDB without interpretation.
An option to blacklist (ignore) packets of certain formats intrepreted elsewhare would be nice.

This would "future proof" the RuuviCollector allowing new formats to be stored without need to modify the collector instead places the responsibility of the interpretation of the message on a subsequent application retrieving the data from the database.

This would also allow custom packets to be stored as created by custom firmware.

Consider :

1) The currently preliminary proposed format 08.  
https://f.ruuvi.com/t/proposal-for-secure-data-format/3756

2) Your own proposal for dynamic data format
https://f.ruuvi.com/t/proposal-for-secure-data-format/3756

3) A lower resolution format reducing the size most measurement fields allowing for increase in size of count fields like movement counter, additional fields for additional sensors or previous values while still remaining within the advertisement length limit.

4) theBASTI0N proposed alternating PacketA and Packet B

5) Secure Shuffling schedules beacons to change the data that they broadcast (major, minor, MAC-address) on regular basis. 
https://support.kontakt.io/hc/en-gb/articles/206762009

I am considering implementing :
A) A C0 format which reports the configuration to be transmitted every 100 packets.
as discussed at 
https://f.ruuvi.com/t/packet-formats-new-tag-status-configuration-packet/3797 

B) A 06 format a one byte extension to 05 containing temperature/humidity delta indicators as discussed at https://f.ruuvi.com/t/packet-formats-new-tag-status-configuration-packet/3797

C) A variant of an existing format with solar incidence as reported by a GA1A1s202wp log sensor replacing some combination of atmospheric pressure, batteryVoltage&eTXpower or most significant bytes of MAC (leaving remaining  bytes for beacon identification)
https://cdn-learn.adafruit.com/downloads/pdf/adafruit-ga1a12s202-log-scale-analog-light-sensor.pdf

Thank you for your consideration

**Comment by ojousima** [comment]
As a quick note, I looked into this a while ago and it seemed that InfluxDB didn't support storing strings as values. I'm not sure if the data payload could be represented as a really big integer, though. 

Even if the data can be represented as an integer, InfluxDB probably cannot use the time series compression on data (or even worse, it might do lossy compression, I don't know enough about internals of InfluxDB).

**Comment by DG12** [comment]
Perhaps for influx a series of integer fields
" InfluxDB stores all integers as signed int64 data types. "

Or stored into a SQL (MySQL, SQLlite ) database or 
even output to a binary file(s) which could be lifetime managed with logrotate

**Comment by Scrin** [comment]
This is actually loosely related to what I've been planning to do with the Ruuvi Gateway; I'm planning on creating a new application (actually.. I started prototyping already) that receives the (raw) data from the gateway (either HTTP POST or MQTT) and process+store it to InfluxDB in the same format as RuuviCollector, making it a convenient drop-in replacement for those who want to switch from a raspberry running RuuviCollector to that.

When that's done I'm planning to add HTTP POST and/or MQTT support to RuuviCollector (or make a separate application) to make it possible to use RuuviCollector (or the separate application) as a replacement for the gateway, which in turn means it'll send any data from RuuviTags, not just the supported formats. Perhaps this is something you could use?

InfluxDB does support strings, but they're not really that well compressed and kind of weird to have in a TSDB in the first place, so some processing should be done before long term storage anyway. This could be done either directly by having an application receive the data with HTTP POST or MQTT. You could even just have a simple bash script subscribe to the MQTT and process your custom data for long-term storage.

**Comment by Scrin** [comment]
[ruuvi-go-gateway](https://github.com/Scrin/ruuvi-go-gateway) has now reached reasonable stability to recommend using it, currently it supports sending all manufacturer-specific data with company identifier 0x0499 wither over HTTP POST or MQTT. If you have a use for a feature not yet supported (such as sending all manufacturer specific data instead of limiting to ruuvi-only), feel free to open an issue there
