### ISSUE TITLE
Feature request/idea: TagSocket support

### ISSUE THREAD

**Issue by jussisallinen** [Scrin/RuuviCollector#49]
**Describe the feature you'd like to have implemented**
tagSocket support for sharing RuuviTag poll data to multiple applications, ie. RuuviCollector and homebridge-ruuvitag receiving data at the same time.

**Describe alternatives you've considered**
-

**Do *you* want to implement this feature?**
No

**Additional info**
https://github.com/klaalo/ifData/tree/master/tagSocket
https://github.com/pakastin/homebridge-ruuvitag

**Comment by Scrin** [comment]
Could you explain a bit why tagSocket support is needed? Do you have a setup that bypasses bluez or some other limitations I'm not aware of?

I realize this is not well documented as it's more of an advanced topic, but RuuviCollector doesn't require exclusive access to bluetooth. Internally RuuviCollector just reads all HCI traffic going through the bluez bluetooth stack so you can run RuuviCollector alongside any other programs that use bluetooth and scan for BLE advertisements.

In such cases the `command.scan=` configuration property should be uncommented and set blank to let the other application(s) manage the scanning, effectively running RuuviCollector in a fully passive mode.

If I'm not completely mistaken, [tagSocket](https://github.com/klaalo/ifData/tree/master/tagSocket) uses [node-ruuvitag](https://github.com/pakastin/node-ruuvitag) which in turn uses [abandonware/noble](https://github.com/abandonware/noble) for BLE, which uses the bluez stack so it all should already work in parallel with RuuviCollector
