### ISSUE TITLE
Running on OS X?

### ISSUE THREAD

**Issue by hkorhola** [Scrin/RuuviCollector#7]
It seems this Ruuvi collector app can't be run on OS X due to lack of Bluez on OS X? Right?

**Comment by Scrin** [comment]
Correct. RuuviCollector uses tools for the bluez (a Linux kernel Bluetooth stack) and directly parses data from them, and thus only works on Linux based OS's. Though it should be relatively low effort to write compatibility for other OS's Bluetooth stacks even though that's a little out-of-scope for the original purpose of the RuuviCollector, which is meant to run on small and inexpensive hardware 24/7, for example on a raspberry pi. Though if someone creates support for other OS's, I'm more than happy to accept a pull request for that.
