### ISSUE TITLE
BUG: Capabilties are not enough after raspberry pi os 12/2022 updates

### ISSUE THREAD

**Issue by hulkk** [Scrin/RuuviCollector#78]
**Describe the bug**
RuuviCollector does not work when run without root privileges after raspberry pi os 12/2022 updates. 

**To Reproduce**
- Make a fresh install with latest updates of raspberry pi os 32-bit
- Install RuuviCollector as per readme
- Run RuuviCollector without root privileges

**Expected behavior**
RuuviCollector works.

**Environment**
OS and device (ie. Raspbian on RaspberryPI): Raspberry pi OS (32-bit) & Raspberry Pi ZeroW 2
Java version (check with java -version): openjdk version "17.0.4" 2022-07-19

**Additional information**
Issue was resolved with adding `cap_sys_rawio` to capabilities.

**Comment by hulkk** [comment]
It seems that this was random issue, fresh install fixed.

**Comment by DG12** [comment]
I have had the same problem setting 
/lib/systemd/system/ruuvicollector.service
User=root. 

Not nice. 
Any ideas?
