### ISSUE TITLE
Retry/Reconnect for InfluxDB

### ISSUE THREAD

**Issue by Scrin** [Scrin/RuuviCollector#8]
InfluxDB may not be available at all times, especially during startup. 
Create retry/reconnect logic to InfluxDBConnection.java

The retry logic should retry a configurable number of times (default maybe 10) before giving up and throwing errors/exiting

**Comment by DG12** [comment]
Retry / connect should not be in java, rather InfluxDBConnection.java should check connection 



Perhaps adding something like:

try {
    Pong response = influxDB.ping();
    if (!response.getVersion().equalsIgnoreCase("unknown")) {
        connected = true;
        LOG.info("Connected to InfluxDB xxxxxx");
    } else {
        connected = false;
        LOG.error("InfluxDB responded unknown to ping. Try influx xxxxxxx ");
    }   
} catch (FreedomoticRuntimeException e) {
    connected = false;
    LOG.error("Cannot connect  InfluxDB for {}", e.getMessage());
}   
to InfluxDBConnection.java after the InfluxDBFactory.connect

+++++++++++++++++++++++++++++
Also I suggest adding

RestartSec=300
to
/lib/systemd/system/ruuvicollector.service

++++++++++++++
When running influxDB on the same machine “requires” should be specified.

/etc/systemd/system/ruuvicollector.service.requires>  ls -log
lrwxrwxrwx 1 36 Dec 30 21:44 influxdb.service > /lib/systemd/system/influxdb.service

i.e. sudo systemctl add-requires ruuvicollector.service influxdb.service



Please add (something like)
RestartSec=300
to
/lib/systemd/system/ruuvicollector.service

**Comment by matthewgardner** [comment]
Retry logic - or graceful shutdown?

**Comment by DG12** [comment]
Please review  #9

**Comment by Scrin** [comment]
Retry with a configurable number of retries (0 for no retry, -1 for infinite retries). And perhaps a configurable interval between the attempts. These configurations should be in the advanced configuration section in the config template.

If it still fails after the retries, there should be a "non-clean" exit with a non-zero exit code for scripts to properly pick up the "failed state"

**Comment by DG12** [comment]
NEVER allow infinite, it is just a bad idea, not even a unrealistic max like 32767.

**Comment by Scrin** [comment]
Infinite is the most convenient choice when not using a service script with an internal retry mechanism

**Comment by DG12** [comment]
Large number of retries hide the problem from the rest of the system (and any observer, including down stream database observers).  This will usually cause the user to initiated full system restart after being very unhappy about the "system" being hung. Consider that if ruuviCollector exits because of a problem it will release the physical and virtual memory, file inodes and other resources for not only itself but also hcitool and hcidump. This will cause significant reallocation of resources by many components of the operating system and may even permit recovery without restart.

Regarding a service script: while  system control managers like systemd or launchd (Mac OS) are very complete, an easily understandable and easy to implement based on a time-of-day scheduler like cron can be effective.

**Comment by Scrin** [comment]
Still better to have an option to retry infinitely rather than potentially going for ages with the collector having simply exited because it gave up retrying. The fact that it *can* be configured as infinite doesn't mean *everyone* should be using infinite in *every* use-case. 

For example in my setup it's more of a fire-and-forget thing, I start it once and leave it running happily there, automatically retry/reconnect in case the network connection is having issues. I only intervene if I receive alerts for no data over a longer period of time, or a noticeable change in the amount of data. Or if the network connection is having other issues (like packet loss or so), but that's not relevant to the collector itself, but more about the setup around it, ie. my home network, or the RPi in general.

**Comment by DG12** [comment]
Of course, your idea of the configuration option is best. (Perhaps with a warning?)  :-)

**Comment by DG12** [comment]
On a personal system note (perhaps to discuss  elsewhere) I have timeout issues nearly every midnight. 
Can you please take a look at details at https://github.com/raspberrypi/linux/issues/2980

**Comment by matthewgardner** [comment]
Ill do a PR for this - please assign to me

**Comment by DG12** [comment]
matthewgardner: Please consider my startup script mentioned at issue #22 which has been successful (for me) before letting RuuviCollector start

**Comment by Scrin** [comment]
Unfortunately Github doesn't let me assign this to you as you are not the creator of this issue and you don't have write access in this repository, but go ahead and create a PR

**Comment by Scrin** [comment]
After some reconsidering I think it's better to default to an "unclean exit" in situations like connectivity issues during startup, as some setups may rely on the service status for monitoring and not realize it doesn't work like that. If someone wants to create a configurable possibility to "always retry and never exit no matter what" I'm happy to accept a PR for that.
