### ISSUE TITLE
influx trouble causes looping

### ISSUE THREAD

**Issue by DG12** [Scrin/RuuviCollector#9]
If there is a problem with influxdb (broken configuration, out of space..). RuuviCollector will crash continuously sucking CPU and perhaps filling log. See #8 

 Please add (something like)

`RestartSec=300`
to
`/lib/systemd/system/ruuvicollector.service
`
++++++++++++++
When running influxDB on the same machine “requires=influxdb.service after=influxdb.service” should be specified.

PS I consider this as deserving a BUG label as "..Malfunctions that should be fixed to comply with the expected behavior" If influx is not running,

**Comment by Scrin** [comment]
Since there is no "official" service script yet, this is kind of out of scope for now. It will be implemented in https://github.com/Scrin/RuuviCollector/issues/22
